<?php
function wpse_141088_upload_dir( $dir ) {
    return array(
        'path'   => $dir['basedir'] . '/users',
        'url'    => $dir['baseurl'] . '/users',
        'subdir' => '/users',
    ) + $dir;
}
//$attach_id = $this->media_handle_sideload( $aFile, $post_id, 'This is optional file title' );
$meta = get_post_meta($post->ID);
$photos = unserialize($meta['photos'][0]);
$count = 0;
if(isset($photos[0])) {
	foreach ($photos as $photo) {
		if($photo['approve'] == 'on') :
			$count++;
		endif;
	}
}


$custom_fields = get_post_custom($post->ID);
$banner1_link = $custom_fields['ba_banner1_link'];
$banner1_img = unserialize($custom_fields['ba_banner1_image'][0]);
$banner2_link = $custom_fields['ba_banner2_link'];
$banner2_img = unserialize($custom_fields['ba_banner2_image'][0]);

$total = $count;
//deg(unserialize($meta['photos'][0]));
if ( ! function_exists( 'wp_handle_upload' ) ) {
    require_once( ABSPATH . 'wp-admin/includes/file.php' );
}
if(logged_in()) {
	$user = new user_info();
	$info = $user->get();

}
if(isset($_FILES['photo_upload'])) :


	$uploadedfile = $_FILES['photo_upload'];
	$upload_overrides = array( 'test_form' => false );
	// Register our path override.
	add_filter( 'upload_dir', 'wpse_141088_upload_dir' );
	// Do our thing. WordPress will move the file to 'uploads/mycustomdir'.
	$movefile = wp_handle_upload( $uploadedfile, $upload_overrides);
	// Set everything back to normal.
	remove_filter( 'upload_dir', 'wpse_141088_upload_dir' );


	if ( $movefile && !isset( $movefile['error'] ) ) {
	    /* success */

		$fileurl = $movefile['file'];

		// $filename should be the path to a file in the upload directory.
		$filename = $fileurl;

		// The ID of the post this attachment is for.
		$parent_post_id = $post->ID;

		// Check the type of file. We'll use this as the 'post_mime_type'.
		$filetype = wp_check_filetype( basename( $filename ), null );

		// Get the path to the upload directory.
		$wp_upload_dir = wp_upload_dir();

		// Prepare an array of post data for the attachment.
		$attachment = array(
			'guid'           => $wp_upload_dir['url'] . '/' . basename( $filename ),
			'post_mime_type' => $filetype['type'],
			'post_title'     => preg_replace( '/\.[^.]+$/', '', basename( $filename ) ),
			'post_content'   => '',
			'post_status'    => 'inherit'
		);

		// Insert the attachment.
		$attach_id = wp_insert_attachment( $attachment, $filename, $parent_post_id );

		// Make sure that this file is included, as wp_generate_attachment_metadata() depends on it.
		require_once( ABSPATH . 'wp-admin/includes/image.php' );

		// Generate the metadata for the attachment, and update the database record.
		$attach_data = wp_generate_attachment_metadata( $attach_id, $filename );

		wp_update_attachment_metadata( $attach_id, $attach_data );


		/* add meta options to the gallery */


		/* admin support */


		$newPhoto = array(
			'url_id' => $attach_id,
			'url' => $movefile['url'],
			'approve' => $info['administrator'] ? 'on' : '',
		);
		$photos[] = $newPhoto;

		update_post_meta( $post->ID, 'photos', $photos);








		$redirect = "<script type='text/javascript'>
			window.location.href = '".get_the_permalink($post->ID).'?success=1'."'
		</script>";

	} else {
	    /**
	     * Error generated by _wp_handle_upload()
	     * @see _wp_handle_upload() in wp-admin/includes/file.php
	     */

	}
endif;





?>

<?php get_header(); ?>
<?php echo $redirect ?>
<!-- start content -->
<div id="content" class="community-subpage gallery">

	<!-- start gallery section  -->
	<div class="gallery-section gallery-detail">
		<!-- start gallery top inner -->
		<div class="gallery-top-inner">
			<div class="container">
				<!-- Start Bredcrumb -->
				<div class="breadcrumb-wrapper">

					<ol vocab="http://schema.org/" typeof="BreadcrumbList">
						<?php spinal_breadcrumb() ?>
					</ol>

				</div>
				<!-- End Bredcrumb -->

				<div class="row">
					<!-- Start description wrapper -->
					<div class="description-wrapper col-lg-12 col-md-12 col-sm-12 col-xs-12">

						<h1>
							<?php the_title() ?>
						</h1>
						<div class="gallery-description">
							<?php echo $meta['short'][0] ?>
						</div>

					</div>
					<!-- End description wrapper -->
				</div>
			</div>
		</div>
		<!-- end gallery top inner -->

		<!-- start gallery bottom inner -->
		<div class="gallery-bottom-inner">
			<div class="container">
				<div class="row">

					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<!-- start upload photo -->
						<a href="#fancybox-add-idea" class="upload-photo">
							<i class="cross"></i>
							<div>
								Upload your
								own photo
							</div>
						</a>


						<div id="fancybox-add-idea" class="avatar-popup">
							<h3>Upload Photo</h3>
							<div class="avatar-inner">
								<form id="add-topic" class="sing-up-general clearfix" method="POST" enctype="multipart/form-data">
									<div class="col-md-12">

										<div class="chose-wrapper upload-button" style="position: relative;cursor:pointer">

												<input type="file" id="topic" accept="image/*" name="photo_upload" style="height:100%;">
                                                <span><i class="fa fa-plus"></i>select from files</span>
											</div>


									</div>
                                    <div class="col-md-12">
                                        <p class="upload-image-notice">
                                            Note: Pictures uploaded to this gallery <br> will be reviewed before making them public
                                        </p>
                                    </div>
									<div class="col-md-12">
										<input type="submit" name="add-idea" value="Add Photo">
									</div>

								</form>
							</div>
						</div>
						<!-- end upload photo -->
						<!-- start grid -->
						<div class="grid clearfix">

							<!-- .grid-sizer empty element, only used for element sizing -->
							<div class="gutter-sizer"></div>

							<?php
							/* Loop main images for this gallery
							------------------------------------------- */
							if($total > 0) :
                                $n = 0;
								foreach ($photos as $photo) :

									$atachmentID = $photo['url_id'];
									$url = $photo['url'];
									$aprove = $photo['approve'] == 'on' ? true : false;
									if($aprove) :
									 ?>

									<div class="grid-item">
										<div class="img-wrapper">
											<a href="#go-to-iframe" class="activate-slider iframe" data-index="<?php echo $n ?>"><i class="fa fa-arrows"></i></a>
											<img src="<?php echo $url  ?>" alt="img">
										</div>
									</div>

									<?php
                                    $n++;
									endif;
								endforeach;
							endif;
							/* END Loop main images for this gallery
							------------------------------------------- */
							 ?>

						</div>
						<!-- end grid -->
					</div>
				</div>

				<div class="row">
					<div class="col-md-12 clearfix">
						<a href="<?php echo page('gallery') ?>" class="back back-gallery"><i class="fa fa-angle-left"></i>back to galleries</a>

					</div>
				</div>
			</div>
		</div>
		<!-- end gallery bottom inner -->
		<?php

		/* Gallery popup lightbox
		---------------------------------------------------------------------- */
		?>
		<div id="go-to-iframe">
			<div class="popup-inner">
				<div class="options-wrapper clearfix">

					<div class="pull-right close-popup-wrapper">
						<span>Close</span> <i class="close-popup"></i>
					</div>

					<div class="on-off-wrapper pull-right clearfix hidden-xs">

						<div class="onoffswitch pull-right">
							<input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked>
							<label class="onoffswitch-label active" for="myonoffswitch">
								<span class="onoffswitch-inner"></span>
								<span class="onoffswitch-switch"></span>
							</label>
						</div>

						<div class="title-text pull-right">
							Slideshow
						</div>

					</div>

				</div>
				<!-- Start slider-->
				<div class="product-slider">
					<?php
					/* Loop main images
					------------------------------------------- */
					if(count($photos) > 0) :
						foreach ($photos as $key => $photo) :

							  $atachmentID = $photo['url_id'];
							  $url = $photo['url'];
							  $aprove = $photo['approve'] == 'on' ? true : false;
							  if($aprove) :
							   ?>

								<div>
									<img src="<?php echo $url  ?>" alt="slide1">
								</div>

								<?php
							endif;
						endforeach;
					endif;
					/* END Loop main images
					------------------------------------------- */
					 ?>
				</div>

				<div class="slider-nav-container">

					<div class="product-slider-nav">
						<?php
						/* Loop thumb images
						------------------------------------------- */
						if(count($photos) > 0) :
							foreach ($photos as $photo) :

								  $atachmentID = $photo['url_id'];
								  $url = $photo['url'];
								  $aprove = $photo['approve'] == 'on' ? true : false;
								  $thumb = featured_image($atachmentID, 'spinal-thumb-home-news');
								  if($aprove) :

						 		  ?>

									<div>
										<div class="inner-thumb">
											<img src="<?php echo $thumb  ?>" alt="slide">
											<span class="overlay-img"></span>
										</div>
									</div>

									<?php
								endif;
							endforeach;
						endif;
						/* END Loop thumb images
						------------------------------------------- */
						 ?>
					</div>
				</div>
			</div>
			<!-- End slider-->
		</div>
	</div>
	<!-- end gallery section  -->
    <div>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <br><br>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pull-left">
                	<div class="article-banner cf">
                		<?php 
                		if(!empty($banner1_img['url'])){ ?>
                		<a target="_blank" style="background: url(<?php echo $banner1_img['url'] ?>);" href="<?php echo $banner1_link[0] ?>"></a>
                		<?php }
                		?>
                		<?php 
                		if(!empty($banner2_img['url'])){ ?>
                		<a target="_blank" style="background: url(<?php echo $banner2_img['url'] ?>);" href="<?php echo $banner2_link[0] ?>"></a>
                		<?php }
                		?>
                	</div>
                    <?php include_once('comments.php') ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end content -->


<?php get_footer() ?>
